### ISSUE TITLE
SSH access to different containers in the same cluster

### ISSUE THREAD

**Issue by johnanders123** [springload/ecs-tool#10]
Is it possible to manually manipulate which container you end up if you want to be on two containers in the same cluster at the same time? 

Can this feature be added to the ecs-tool ssh feature (thank you so much for adding this feature)

**Comment by ekini** [comment]
No, it just gets the first one, I assume randomly. If the containers list order is random, how would you choose the right one?

For this "extra" stuff maybe it's easier to use `aws-ssh ssh`, which will ssh into the ec2 instance, and from there manual discovery of containers can be performed by running `docker ps`.
