### ISSUE TITLE
ecs-tool ssh not working

### ISSUE THREAD

**Issue by johnanders123** [springload/ecs-tool#11]
Can we please restore ecs-tool ssh? While it's not needed on every project it's hard to run rails without it for example.

At the moment we need to do the following to run rails console.

1. aws-ssh ssh -i [INSTANCE_ID] -p [PROFILE]
2. docker exec -ti [CONTAINER_ID] sh
3. /sbin/ssm-parent run -e -p /[PROJECT]/common/ -p /$PROJECT/$ENVIRONMENT -r -- rails c

**Comment by jaedb** [comment]
Has there been any progress with this issue?

**Comment by jesserockz** [comment]
@jaedb I have just fixed it and we are working on redeployment of some of the infrastructure.

**Comment by jaedb** [comment]
@jesserockz awesome, thanks for the update. When can we expect this to be operational for our project?
