### ISSUE TITLE
Error decoding ejson occasionally

### ISSUE THREAD

**Issue by jesserockz** [springload/ecs-tool#14]
Sometimes on CircleCI our deploy step is failing with:
```
FATAL[0000] can't write the ssm parameter error=processor command exited with an error: got invalid json from the processor output: unexpected end of JSON input
```

I can usually rerun the job with no changes and it will work fine.

**Comment by ekini** [comment]
I've seen that once. Not sure - might be some circleci glitch?

**Comment by jesserockz** [comment]
Yeah probably, I have seen it maybe once in 2 weeks, maybe total of 3 or 4 times.

**Comment by jesserockz** [comment]
I am seeing this in GitHub Action workflows too, so not specifically CircleCI

**Comment by ekini** [comment]
The most common use case for this has been fixed by https://github.com/springload/ecs-tool/pull/19

I haven't been able to reproduce this issue reliably in a CI or locally.

**Comment by jaedb** [comment]
I've also experienced this periodically; about 10% of the time. What is the status of getting #19 merged?

**Comment by ekini** [comment]
That's been merged and release, here is an example of how to use it: https://github.com/springload/ecs-tool/blob/master/example.toml#L27
