### ISSUE TITLE
Rewriting images tags for all containers definition

### ISSUE THREAD

**Issue by ohmer** [springload/ecs-tool#23]
Hi there,

I understand from https://github.com/springload/ecs-tool/blob/7e1eb8739532c82ddfc38891e9ecd0e5753e9445/lib/deploy.go#L94 and following, that all containers definitions image tags are rewritten. It happens that I don't want that to happen for a side car container. Is it the expected behavior?

If that the case, I think it should only be done for the container definition matching `container_name` in the .toml.

Could you clarify please?

Cheers!

**Comment by ekini** [comment]
Actually, I'm thinking I can add `--image-tags` flag that can be specified several times for each container definition and only modify the corresponding one.
```bash
  --image-tags Modifies the docker image tags in container definitions. Can be specified several times, one for each container definition. I.e. if there are 2 containers and --image-tags is set once to "new", then the image tag of the first container will be modified, leaving the second one untouched.
```

**Comment by ohmer** [comment]
Hi @ekini,

Thanks for looking into the issue. This does not give me the flexibility that I am looking for and I am going to replace `ecs-tool` with AWS provided Github Actions https://github.com/aws-actions/amazon-ecs-render-task-definition / https://github.com/aws-actions/amazon-ecs-deploy-task-definition.

Cheers,
