### ISSUE TITLE
Interactive commands?

### ISSUE THREAD

**Issue by editkid** [springload/ecs-tool#5]
Is it possible to run interactive commands? E.g.

```
$ ecs-tool run  -e neue -p peter -- ./manage.py shell
  INFO[0000] Using config file: /Users/peter/Webdev/klim/infra/ecs-neue.toml
  INFO[0001] Waiting for the task to finish task_definition=klim-neue-ecs-app
  INFO[0016] Container exited          container_name=app-httpd exit_code=0
  INFO[0016] Container exited          container_name=app exit_code=0
```

They seem to just time out.

**Comment by editkid** [comment]
Ah, can just SSH in to server. :) Ignore this issue please.

**Comment by editkid** [comment]
Re-opening this as it seems I can't/shouldn't SSH into the server directly anymore. So, in that case it'd be amazing to be able to run interactive commands.

E.g. sometimes I even just `./manage.py shell` and check a few things in Production. Is this possible with `ecs-tool`?

Thanks! 🗿

**Comment by editkid** [comment]
CC @johnanders123

**Comment by johnanders123** [comment]
As far as I understand you can't easily if at all. I'll be easier to add flags to your manage.py commands or run ecs-tool multiple times. If you give some examples here of what you're trying to do I can see whether there's a way to stitch it together. @ekini is on leave at the moment and won't be back to next week.

**Comment by editkid** [comment]
Going to add some flags for now. It doesn't cover all bases, especially the `./manage.py shell` where you drop into a Python interactive shell, but it will cover what I need for now.

Interesting though. So is giving SSH access against current policy/thinking, is that right? Just checking.

Thanks! :v:

**Comment by editkid** [comment]
Any ideas here @ekini? For Klim we sometimes have to run manual commands in an interactive Python shell... using `./manage.py shell`. So this won't be possible anymore going forward?

**Comment by editkid** [comment]
Also for debugging in a live/hosted environment it's super valuable to be able to do this.
